services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: smartdoc_postgres

    environment:
      POSTGRES_USER: smartdoc_user
      POSTGRES_PASSWORD: smartdoc_password
      POSTGRES_DB: smartdoc_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build: .
    container_name: smartdoc_app

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql+psycopg://smartdoc_user:smartdoc_password@postgres:5432/smartdoc_db
      OLLAMA_BASE_URL: http://host.docker.internal:11434

    depends_on:
      - postgres

volumes:
  postgres_data: